#!/usr/bin/env python3

import argparse
import glob
import sys
import warnings

warnings.filterwarnings("ignore")

import requests
import faiss
import numpy as np

from sentence_transformers import SentenceTransformer
from pypdf import PdfReader


def parse_arguments():
    parser = argparse.ArgumentParser(
        description="Multi-PDF RAG System using local llama.cpp server"
    )

    parser.add_argument(
        "--pdf-dir",
        default="pdfs/realestate",
        help="Folder containing PDFs"
    )

    parser.add_argument(
        "--llama-url",
        default="http://localhost:8080/v1/chat/completions",
        help="llama.cpp OpenAI-compatible chat completions URL"
    )

    parser.add_argument(
        "--chunk-size",
        type=int,
        default=300,
        help="Number of words per chunk"
    )

    parser.add_argument(
        "--overlap",
        type=int,
        default=50,
        help="Number of overlapping words between chunks"
    )

    parser.add_argument(
        "--top-k",
        type=int,
        default=5,
        help="Number of document chunks to retrieve"
    )

    parser.add_argument(
        "--max-tokens",
        type=int,
        default=300,
        help="Maximum number of tokens generated by llama.cpp"
    )

    return parser.parse_args()


def load_pdf(path):
    """Extract text from a single PDF file."""

    reader = PdfReader(path)

    text = ""

    for page in reader.pages:
        page_text = page.extract_text()

        if page_text:
            text += page_text + "\n"

    return text


def chunk_text(text, chunk_size, overlap):
    """Split text into overlapping word-based chunks."""

    if overlap >= chunk_size:
        raise ValueError(
            "overlap must be smaller than chunk_size"
        )

    words = text.split()

    chunks = []

    start = 0

    while start < len(words):

        end = start + chunk_size

        chunk = " ".join(words[start:end])

        if chunk.strip():
            chunks.append(chunk)

        start += chunk_size - overlap

    return chunks


def check_llama_server(server_url):
    """Check whether llama.cpp is running."""

    health_url = server_url.replace(
        "/v1/chat/completions",
        "/health"
    )

    print("\nChecking llama.cpp server...")
    print(f"  {server_url}")

    try:

        response = requests.get(
            health_url,
            timeout=5
        )

        if response.ok:

            print("  llama.cpp server: OK")

            return True

        print(
            f"  llama.cpp health check returned "
            f"HTTP {response.status_code}"
        )

        return False

    except requests.exceptions.ConnectionError:

        print("  ERROR: Cannot connect to llama.cpp.")
        print()
        print("  Make sure your llama.cpp server is running.")
        print("  Example:")
        print()
        print("    ./llama-server ... --port 8080")
        print()

        return False

    except Exception as e:

        print(f"  WARNING: Health check failed: {e}")

        return False


def ask_llama(
    server_url,
    query,
    context,
    max_tokens
):
    """Send a question and RAG context to llama.cpp."""

    messages = [
        {
            "role": "system",
            "content": (
                "You are a helpful real estate assistant.\n\n"
                "Answer the user's question using the provided "
                "document context.\n\n"
                "Use only information supported by the context. "
                "Do not invent facts.\n\n"
                "If the answer cannot be determined from the "
                "provided documents, say:\n"
                "\"I don't have enough information in the "
                "provided documents.\""
            )
        },
        {
            "role": "user",
            "content": (
                f"DOCUMENT CONTEXT:\n\n"
                f"{context}\n\n"
                f"QUESTION:\n\n"
                f"{query}"
            )
        }
    ]

    payload = {
        "messages": messages,
        "max_tokens": max_tokens,
        "temperature": 0.2,
        "stream": False
    }

    try:

        response = requests.post(
            server_url,
            json=payload,
            timeout=300
        )

        response.raise_for_status()

        result = response.json()

        # OpenAI-compatible llama.cpp response
        answer = result["choices"][0]["message"]["content"]

        return answer.strip()

    except requests.exceptions.ConnectionError:

        print()
        print("ERROR: Could not connect to llama.cpp.")
        print(f"URL: {server_url}")
        print()
        print("Make sure llama.cpp is running on port 8080.")
        sys.exit(1)

    except requests.exceptions.Timeout:

        print()
        print("ERROR: llama.cpp request timed out.")
        sys.exit(1)

    except requests.exceptions.HTTPError as e:

        print()
        print("ERROR: llama.cpp returned an HTTP error:")
        print(e)

        try:
            print(response.text)
        except Exception:
            pass

        sys.exit(1)

    except KeyError:

        print()
        print("ERROR: Unexpected llama.cpp response:")
        print(result)
        sys.exit(1)

    except Exception as e:

        print()
        print("ERROR calling llama.cpp:")
        print(e)
        sys.exit(1)


def main():

    args = parse_arguments()

    # =========================================================
    # 1. Load PDFs
    # =========================================================

    print()
    print("=" * 80)
    print("MULTI-PDF RAG SYSTEM")
    print("=" * 80)

    print()
    print(f"PDF directory: {args.pdf_dir}")

    pdf_files = glob.glob(
        f"{args.pdf_dir}/*.pdf"
    )

    if not pdf_files:

        print()
        print(
            f"ERROR: No PDF files found in "
            f"{args.pdf_dir}"
        )

        sys.exit(1)

    print(
        f"Found {len(pdf_files)} PDF file(s)."
    )

    # =========================================================
    # 2. Extract and chunk PDFs
    # =========================================================

    print()
    print("Loading PDFs...")

    all_chunks = []

    for pdf_file in pdf_files:

        try:

            text = load_pdf(pdf_file)

            if not text.strip():

                print(
                    f"  WARNING: No text extracted from "
                    f"{pdf_file}"
                )

                continue

            chunks = chunk_text(
                text,
                args.chunk_size,
                args.overlap
            )

            all_chunks.extend(chunks)

            print(
                f"  {pdf_file}: "
                f"{len(chunks)} chunks"
            )

        except Exception as e:

            print(
                f"  ERROR processing "
                f"{pdf_file}: {e}"
            )

    if not all_chunks:

        print()
        print("ERROR: No text chunks generated.")

        sys.exit(1)

    print()
    print(
        f"Total chunks: {len(all_chunks)}"
    )

    # =========================================================
    # 3. Initialize embedding model
    # =========================================================

    print()
    print("Initializing embedding model...")

    embedder = SentenceTransformer(
        "sentence-transformers/all-MiniLM-L12-v2"
    )

    print("Embedding documents...")

    embeddings = embedder.encode(
        all_chunks,
        convert_to_numpy=True,
        show_progress_bar=True
    )

    # =========================================================
    # 4. Build FAISS index
    # =========================================================

    print()
    print("Building FAISS index...")

    dimension = embeddings.shape[1]

    index = faiss.IndexFlatL2(
        dimension
    )

    index.add(
        embeddings
    )

    print(
        f"FAISS vectors: {index.ntotal}"
    )

    print(
        f"Embedding dimension: {dimension}"
    )

    # =========================================================
    # 5. Check llama.cpp
    # =========================================================

    if not check_llama_server(
        args.llama_url
    ):

        print()
        print(
            "WARNING: llama.cpp server could "
            "not be verified."
        )

        print(
            "The program will continue, but "
            "questions may fail."
        )

    # =========================================================
    # 6. Display configuration
    # =========================================================

    print()
    print("=" * 80)
    print("CONFIGURATION")
    print("=" * 80)

    print(
        f"LLM server:     {args.llama_url}"
    )

    print(
        f"PDF directory:  {args.pdf_dir}"
    )

    print(
        f"PDF files:      {len(pdf_files)}"
    )

    print(
        f"Chunks:         {len(all_chunks)}"
    )

    print(
        f"Chunk size:     {args.chunk_size} words"
    )

    print(
        f"Chunk overlap:  {args.overlap} words"
    )

    print(
        f"Retrieval K:    {args.top_k}"
    )

    print(
        f"Max tokens:     {args.max_tokens}"
    )

    print("=" * 80)

    print()
    print(
        "RAG system ready."
    )

    print(
        "Type 'exit' to quit."
    )

    print()

    # =========================================================
    # 7. Interactive question loop
    # =========================================================

    while True:

        try:

            query = input(
                "Your question: "
            ).strip()

        except (
            KeyboardInterrupt,
            EOFError
        ):

            print()
            print("Goodbye!")

            break

        if not query:
            continue

        if query.lower() in [
            "exit",
            "quit",
            "q"
        ]:

            print("Goodbye!")

            break

        # =====================================================
        # 8. Embed the user's question
        # =====================================================

        query_embedding = embedder.encode(
            [query],
            convert_to_numpy=True
        )

        # =====================================================
        # 9. Search FAISS
        # =====================================================

        k = min(
            args.top_k,
            len(all_chunks)
        )

        distances, indices = index.search(
            query_embedding,
            k
        )

        retrieved_chunks = []

        for i in indices[0]:

            if i >= 0:

                retrieved_chunks.append(
                    all_chunks[i]
                )

        # =====================================================
        # 10. Build context
        # =====================================================

        context_parts = []

        for i, chunk in enumerate(
            retrieved_chunks,
            1
        ):

            context_parts.append(
                f"[Document Chunk {i}]\n"
                f"{chunk}"
            )

        context = (
            "\n\n"
            "------------------------------"
            "\n\n"
        ).join(context_parts)

        # =====================================================
        # 11. Send request to llama.cpp
        # =====================================================

        print()
        print("Searching documents...")
        print(
            f"Retrieved {len(retrieved_chunks)} "
            f"relevant chunks."
        )

        print()
        print("Asking llama.cpp...")

        answer = ask_llama(
            args.llama_url,
            query,
            context,
            args.max_tokens
        )

        # =====================================================
        # 12. Display answer
        # =====================================================

        print()
        print("=" * 80)
        print("ANSWER")
        print("=" * 80)

        print(answer)

        # =====================================================
        # 13. Display sources
        # =====================================================

        print()
        print("=" * 80)
        print("SOURCES")
        print("=" * 80)

        for i, chunk in enumerate(
            retrieved_chunks[:3],
            1
        ):

            # Get a shorter preview
            preview = chunk[:500]

            print()
            print(
                f"[{i}] {preview}"
            )

            if len(chunk) > 500:
                print("...")

        print()
        print("=" * 80)
        print()


if __name__ == "__main__":
    main()